### ISSUE TITLE
bossquery whitespace sensitivity

### ISSUE THREAD

**Issue by dcunning11235** [dkirkby/bossdata#36]
When passing a command-line argument like `--what 'PLATE,MJD ,FIBER,CLASS,Z'` to `bossquery` the error

```
Invalid column name MJD .
```

is thrown.  Removing ws following MJD solves this.  Need to fix this.

More generally, ensure ws is not an issue for command line args to `boss*` commands.

**Comment by dkirkby** [comment]
I'm downgrading this from a "bug" since the issue does not lead to incorrect answers or crashes given valid input.  The argparse help string currently says "List of comma-separated columns to return from the query.", so there is no guarantee that white space is allowed.

I am sure there are lots of places where we could improve input validation / scrubbing and we will never achieve perfection here.  However, it is still good to fix issues like this as they arise and when they are easy to fix.  Here is a [good starting point](http://stackoverflow.com/questions/4071396/split-by-comma-and-strip-whitespace-in-python) for this issue.
