### ISSUE TITLE
Regarding methods & lite/full data files

### ISSUE THREAD

**Issue by belaa** [dkirkby/bossdata#47]
If you downloaded both "lite" and "full" versions (first lite and then full), do all subsequent methods you call automatically use data from the "lite" file?

**Comment by dcunning11235** [comment]
I have a pull request pending for issue https://github.com/dkirkby/bossdata/issues/7 (I see that the merge needs to be done manually, so I will try to clean that up) that will change this behavior (see link for a table describing the future behavior.)

With the current version the behavior is governed only by the --full flag (or the lack thereof):  --full uses the full DB, otherwise the lite DB is used.

EDIT:  And actually, this is for bossquery.  For bossplot, this is determined by other parameters (e.g. if you specify exposures), though this behavior will also be altered with future merge.

**Comment by dcunning11235** [comment]
The changes referenced above have been merged into the master branch (as of mid-day-ish yesterday)
