### ISSUE TITLE
Specifying camera in spec module

### ISSUE THREAD

**Issue by belaa** [dkirkby/bossdata#84]
In the [docs](http://bossdata.readthedocs.org/en/latest/src/bossdata.spec.html) it says that the camera parameter in `get_exposure_hdu(exposure_index,camera)` takes a string that specifies: 

camera(str) -- Which camera to use. Must be one of b1,b2,r1,r2.

However the only parameter values it seems to be taking are 'red' or 'blue.' 

Question: The way it is now, is it returning the sum of the red/blue cameras for each exposure?

**Comment by dkirkby** [comment]
There are actually two versions of the documentation hosted by readthedocs: "latest" and "stable", which correspond to the github master branch and the latest version released on pypi.  The inconsistency you noticed is because readthedocs gives you "latest" by default, but this is a change that is in the master branch but not yet released on pypi.  You can select "stable" by editing your URL, e.g.

```
http://bossdata.readthedocs.org/en/latest/src/bossdata.spec.html
```

becomes:

```
http://bossdata.readthedocs.org/en/stable/src/bossdata.spec.html
```

or else by using the green pull-down menu in the bottom left corner of any page.

If you are using `bossdata` from a `pip install` its is good idea to bookmark `http://bossdata.readthedocs.org/en/stable` in your browser to avoid these kinds of problems.

**Comment by belaa** [comment]
Ok great. Thanks!
